In [23]:
import numpy as np
import pandas as pd
import fastf1 as f1
from data_profiling import ProfileReport
import seaborn as sns
import matplotlib.pyplot as plt
import os

In [15]:
sessions = dict()
for i in range(2020, 2026):
    races = list()
    j=0
    while True:
        j+=1
        try:
            races.append(f1.get_session(i, j, 5))
        except ValueError:
            print(i, "done")
            break
    sessions[i]=races.copy()

2020 done
2021 done
2022 done
2023 done
2024 done
2025 done

# Load

In [16]:

for key, value in sessions.items():
    for k in value:
        k.load(laps=True, telemetry=False, weather=False, messages=False)
        print("*"*20)
        print(f"{key}, {k} done")
        print("*"*20)

    print("*"*20)
    print(f"{key} done")
    print("*"*20)

core           INFO 	Loading data for Austrian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '99'
core        WARNING 	Driver  8: Lap timing integrity check failed for 1 lap(s)
core           INFO 	Finished loading data for 20 drivers: ['77', '16', '4', '44', '55', '11', '10', '31', '99', '5', '6', '26', '23', '7', '63', '8', '20', '18', '3', '33']
core           INFO 	Loading data for Styrian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2020, 2020 Season Round 1: Austrian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 44 completed the race distance 00:00.057000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '23', '4', '11', '18', '3', '55', '26', '7', '20', '8', '99', '10', '63', '6', '31', '16', '5']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2020, 2020 Season Round 2: Styrian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '20'
core        WARNING 	Fixed incorrect tyre stint information for driver '8'
core        WARNING 	Driver 44 completed the race distance 00:00.098000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '77', '18', '23', '5', '11', '3', '55', '20', '16', '26', '4', '31', '7', '8', '99', '63', '6', '10']
core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2020, 2020 Season Round 3: Hungarian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 27)
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '16', '3', '4', '31', '10', '23', '18', '5', '77', '63', '55', '99', '6', '8', '7', '26', '20', '27']
core           INFO 	Loading data for 70th Anniversary Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2020, 2020 Season Round 4: British Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 33 completed the race distance 00:00.036000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['33', '44', '77', '16', '23', '18', '27', '31', '4', '26', '10', '5', '55', '3', '7', '8', '99', '63', '6', '20']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2020, 2020 Season Round 5: 70th Anniversary Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 44 completed the race distance 00:00.071000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '77', '18', '11', '55', '5', '23', '10', '4', '3', '26', '31', '7', '20', '99', '63', '6', '8', '16']
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2020, 2020 Season Round 6: Spanish Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '33'
core        WARNING 	Fixed incorrect tyre stint information for driver '23'
core        WARNING 	Fixed incorrect tyre stint information for driver '4'
core        WARNING 	Fixed incorrect tyre stint information for driver '7'
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 55)
core        WARNING 	Driver 44 completed the race distance 00:00.105000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '3', '31', '23', '4', '10', '18', '11', '26', '7', '5', '16', '8', '6', '20', '99', '63', '55']
core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2020, 2020 Season Round 7: Belgian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 10 completed the race distance 00:00.067000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['10', '55', '18', '4', '77', '3', '44', '31', '26', '11', '6', '8', '7', '63', '23', '99', '33', '16', '20', '5']
core           INFO 	Loading data for Tuscan Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2020, 2020 Season Round 8: Italian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 44 completed the race distance 00:00.070000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '23', '3', '11', '4', '26', '16', '7', '5', '63', '8', '18', '31', '6', '20', '99', '55', '33', '10']
core           INFO 	Loading data for Russian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2020, 2020 Season Round 9: Tuscan Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 77 completed the race distance 00:00.039000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['77', '33', '44', '11', '3', '16', '31', '26', '10', '23', '99', '20', '5', '7', '4', '6', '8', '63', '55', '18']
core           INFO 	Loading data for Eifel Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2020, 2020 Season Round 10: Russian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 44 completed the race distance 00:00.016000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '3', '11', '55', '10', '16', '27', '8', '99', '5', '7', '20', '6', '26', '4', '23', '31', '77', '63']
core           INFO 	Loading data for Portuguese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2020, 2020 Season Round 11: Eifel Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 44 completed the race distance 00:00.098000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '16', '10', '55', '11', '31', '3', '5', '7', '23', '4', '63', '99', '20', '8', '6', '26', '18']
core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2020, 2020 Season Round 12: Portuguese Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 44 completed the race distance 00:00.100000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '3', '26', '16', '11', '55', '4', '7', '99', '6', '5', '18', '8', '23', '63', '33', '20', '31', '10']
core           INFO 	Loading data for Turkish Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2020, 2020 Season Round 13: Emilia Romagna Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 44 completed the race distance 00:00.068000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '11', '5', '16', '55', '33', '23', '4', '18', '3', '31', '26', '10', '77', '7', '63', '20', '8', '6', '99']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2020, 2020 Season Round 14: Turkish Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '23', '4', '55', '10', '3', '77', '31', '16', '26', '63', '5', '6', '7', '99', '20', '11', '18', '8']
core           INFO 	Loading data for Sakhir Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2020, 2020 Season Round 15: Bahrain Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 11 completed the race distance 00:00.111000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['11', '31', '18', '55', '3', '23', '26', '77', '63', '4', '10', '5', '99', '7', '20', '89', '51', '6', '33', '16']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2020, 2020 Season Round 16: Sakhir Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 33 completed the race distance 00:00.087000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['33', '77', '44', '23', '4', '55', '3', '10', '31', '18', '26', '7', '16', '5', '63', '99', '6', '20', '51', '11']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2020, 2020 Season Round 17: Abu Dhabi Grand Prix - Race done
********************
********************
2020 done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '11'
core        WARNING 	Driver 44 completed the race distance 00:00.067000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '77', '4', '11', '16', '3', '55', '22', '18', '7', '99', '31', '63', '5', '47', '10', '6', '14', '9']
core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 1: Bahrain Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 33 completed the race distance 00:01.003000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['33', '44', '4', '16', '55', '3', '10', '18', '31', '14', '11', '22', '7', '99', '5', '47', '9', '77', '63', '6']
core           INFO 	Loading data for Portuguese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 2: Emilia Romagna Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 44 completed the race distance 00:00.050000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '77', '11', '4', '16', '31', '14', '3', '10', '55', '99', '5', '18', '22', '63', '47', '6', '9', '7']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 3: Portuguese Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 44 completed the race distance 00:00.083000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '77', '16', '11', '3', '55', '4', '31', '10', '18', '7', '5', '63', '99', '6', '14', '47', '9', '22']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 4: Spanish Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 16)
core        WARNING 	Driver 33 completed the race distance 00:00.058000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['33', '55', '4', '11', '5', '10', '44', '18', '31', '99', '7', '3', '14', '63', '6', '22', '9', '47', '77', '16']
core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 5: Monaco Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '11'
core        WARNING 	Fixed incorrect tyre stint information for driver '47'
core        WARNING 	Driver 11 completed the race distance 00:00.028000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['11', '5', '10', '16', '4', '14', '22', '55', '3', '7', '99', '77', '47', '9', '44', '6', '63', '33', '18', '31']
core           INFO 	Loading data for French Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 6: Azerbaijan Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 33 completed the race distance 00:00.047000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['33', '44', '11', '77', '4', '3', '10', '14', '5', '18', '55', '63', '22', '31', '99', '16', '7', '6', '47', '9']
core           INFO 	Loading data for Styrian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 7: French Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 33 completed the race distance 00:00.152000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['33', '44', '77', '11', '4', '55', '16', '18', '14', '22', '7', '5', '3', '31', '99', '47', '6', '9', '63', '10']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 8: Styrian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 33 completed the race distance 00:00.061000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['33', '77', '4', '44', '55', '11', '3', '16', '10', '14', '63', '22', '18', '99', '7', '6', '5', '47', '9', '31']
core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 9: Austrian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 44 completed the race distance 00:00.025000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '16', '77', '4', '3', '55', '14', '18', '31', '22', '10', '63', '99', '6', '7', '11', '9', '47', '5', '33']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 10: British Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 31 completed the race distance 00:00.068000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['31', '44', '55', '14', '10', '22', '6', '63', '33', '7', '3', '47', '99', '9', '4', '77', '11', '16', '18', '5']
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 11: Hungarian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '33'
core        WARNING 	Fixed incorrect tyre stint information for driver '63'
core        WARNING 	Fixed incorrect tyre stint information for driver '6'
core        WARNING 	Fixed incorrect tyre stint information for driver '99'
core        WARNING 	Fixed incorrect tyre stint information for driver '47'
core        WARNING 	Fixed incorrect tyre stint information for driver '9'
core        WARNING 	Fixed incorrect tyre stint information for driver '7'
core           INFO 	Finished loading data for 20 drivers: ['33', '63', '44', '3', '5', '10', '31', '16', '6', '55', '14', '77', '99', '4', '22', '47', '9', '7', '11', '18']
core           INFO 	Loading data for Dutch Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 12: Belgian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 33 completed the race distance 00:00.012000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['33', '44', '77', '10', '16', '14', '55', '11', '31', '4', '3', '18', '5', '99', '88', '6', '63', '47', '22', '9']
core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 13: Dutch Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 22)
core        WARNING 	Driver 3 completed the race distance 00:00.086000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['3', '4', '77', '16', '11', '55', '18', '14', '63', '31', '6', '5', '99', '88', '47', '9', '44', '33', '10', '22']
core           INFO 	Loading data for Russian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 14: Italian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 44 completed the race distance 00:00.044000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '55', '3', '77', '14', '4', '7', '11', '63', '18', '5', '10', '31', '16', '99', '22', '9', '6', '47']
core           INFO 	Loading data for Turkish Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 15: Russian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 77 completed the race distance 00:00.079000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['77', '33', '11', '16', '44', '10', '4', '55', '18', '31', '99', '7', '3', '22', '63', '14', '6', '5', '47', '9']
core           INFO 	Loading data for United States Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 16: Turkish Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 33 completed the race distance 00:00.059000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['33', '44', '11', '16', '3', '77', '55', '4', '22', '5', '99', '18', '7', '63', '6', '47', '9', '14', '31', '10']
core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 17: United States Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 33 completed the race distance 00:00.032000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['33', '44', '11', '10', '16', '55', '5', '7', '14', '4', '99', '3', '31', '18', '77', '63', '6', '9', '47', '22']
core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 18: Mexico City Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 44 completed the race distance 00:00.059000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '77', '11', '16', '55', '10', '31', '14', '4', '5', '7', '63', '99', '22', '6', '9', '47', '3', '18']
core           INFO 	Loading data for Qatar Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 19: São Paulo Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 44 completed the race distance 00:00.037000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '14', '11', '31', '18', '55', '16', '4', '5', '10', '3', '22', '7', '99', '47', '63', '9', '6', '77']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 20: Qatar Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 44 completed the race distance 00:00.180000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '77', '31', '3', '10', '16', '55', '99', '4', '18', '6', '14', '22', '7', '5', '11', '9', '63', '47']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 21: Saudi Arabian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 9)
core        WARNING 	Driver 33 completed the race distance 00:00.035000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['33', '44', '55', '22', '10', '77', '4', '14', '31', '16', '5', '3', '18', '47', '11', '6', '99', '63', '7', '9']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2021, 2021 Season Round 22: Abu Dhabi Grand Prix - Race done
********************
********************
2021 done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 16 completed the race distance 00:00.050000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['16', '55', '44', '63', '20', '77', '31', '22', '14', '24', '47', '18', '23', '3', '4', '6', '27', '11', '1', '10']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 1: Bahrain Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 22
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 22)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 47)
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '11', '63', '31', '4', '10', '20', '44', '24', '27', '18', '23', '77', '14', '3', '6', '22', '47']
core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 2: Saudi Arabian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 16 completed the race distance 00:00.140000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['16', '11', '63', '44', '4', '3', '31', '77', '10', '23', '24', '18', '47', '20', '22', '6', '14', '1', '5', '55']
core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 3: Australian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '4', '63', '77', '16', '22', '5', '20', '18', '23', '10', '44', '31', '24', '6', '47', '3', '14', '55']
core           INFO 	Loading data for Miami Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 4: Emilia Romagna Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '11', '63', '44', '77', '31', '23', '18', '14', '22', '3', '6', '47', '20', '5', '10', '4', '24']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 5: Miami Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '63', '55', '44', '77', '31', '4', '14', '22', '5', '3', '10', '47', '18', '6', '20', '23', '24', '16']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 6: Spanish Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '11'
core        WARNING 	Fixed incorrect tyre stint information for driver '55'
core        WARNING 	Fixed incorrect tyre stint information for driver '1'
core        WARNING 	Fixed incorrect tyre stint information for driver '16'
core        WARNING 	Fixed incorrect tyre stint information for driver '63'
core        WARNING 	Fixed incorrect tyre stint information for driver '4'
core        WARNING 	Fixed incorrect tyre stint information for driver '14'
core        WARNING 	Fixed incorrect tyre stint information for driver '44'
core        WARNING 	Fixed incorrect tyre stint information for driver '77'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
core        WARNING 	Fixed incorrect tyre stint information for driver '10'
core        WARNING 	Fixed incorrect tyre stint information for driver '31'
core        WARNING 	Fixed incorrect tyre stint information for driver '3'
core        WARNING 	Fixed incorrect tyre stint information for driver '18'
core        WARNING 	Fixed incorrect tyre stint information for driver '6'
core        WARNING 	Fixed incorrect tyre stint information for driver '24'
core        WARNING 	Fixed incorrect tyre stint information for driver '22'
core        WARNING 	Fixed incorrect tyre stint information for driver '23'
core        WARNING 	Fixed incorrect tyre stint information for driver '47'
core        WARNING 	Fixed incorrect tyre stint information for driver '20'
core           INFO 	Finished loading data for 20 drivers: ['11', '55', '1', '16', '63', '4', '14', '44', '77', '5', '10', '31', '3', '18', '6', '24', '22', '23', '47', '20']
core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 7: Monaco Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '63', '44', '10', '5', '14', '3', '4', '31', '77', '23', '22', '47', '6', '18', '20', '24', '16', '55']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 8: Azerbaijan Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '55', '44', '63', '16', '31', '77', '24', '14', '18', '3', '5', '23', '10', '4', '6', '20', '22', '47', '11']
core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 9: Canadian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['55', '11', '44', '16', '14', '4', '1', '47', '5', '20', '18', '6', '3', '22', '31', '10', '77', '63', '24', '23']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 10: British Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '16'
core        WARNING 	Fixed incorrect tyre stint information for driver '1'
core        WARNING 	Fixed incorrect tyre stint information for driver '44'
core        WARNING 	Fixed incorrect tyre stint information for driver '63'
core        WARNING 	Fixed incorrect tyre stint information for driver '31'
core        WARNING 	Fixed incorrect tyre stint information for driver '47'
core        WARNING 	Fixed incorrect tyre stint information for driver '4'
core        WARNING 	Fixed incorrect tyre stint information for driver '20'
core        WARNING 	Fixed incorrect tyre stint information for driver '3'
core        WARNING 	Fixed incorrect tyre stint information for driver '14'
core        WARNING 	Fixed incorrect tyre stint information for driver '77'
core        WARNING 	Fixed incorrect tyre stint information for driver '23'
core        WARNING 	Fixed incorrect tyre stint information for driver '18'
core        WARNING 	Fixed incorrect tyre stint information for driver '24'
core        WARNING 	Fixed incorrect tyre stint information for driver '10'
core        WARNING 	Fixed incorrect tyre stint information for driver '22'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
core        WARNING 	Fixed incorrect tyre stint information for driver '55'
core        WARNING 	Fixed incorrect tyre stint information for driver '6'
core        WARNING 	Fixed incorrect tyre stint information for driver '11'
core        WARNING 	Driver 16 completed the race distance 00:00.024000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['16', '1', '44', '63', '31', '47', '4', '20', '3', '14', '77', '23', '18', '24', '10', '22', '5', '55', '6', '11']
core           INFO 	Loading data for French Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 11: Austrian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 1 completed the race distance 00:00.041000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '63', '11', '55', '14', '4', '31', '3', '18', '5', '10', '23', '77', '47', '24', '6', '20', '16', '22']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 12: French Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '63', '55', '11', '16', '4', '14', '31', '5', '18', '10', '24', '47', '3', '20', '23', '6', '22', '77']
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 13: Hungarian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '10'
core        WARNING 	Fixed incorrect tyre stint information for driver '22'
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '63', '14', '16', '31', '5', '10', '23', '18', '4', '22', '24', '3', '20', '47', '6', '77', '44']
core           INFO 	Loading data for Dutch Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 14: Belgian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '63', '16', '44', '11', '14', '4', '55', '31', '18', '10', '23', '47', '5', '20', '24', '3', '6', '77', '22']
core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 15: Dutch Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '63', '55', '44', '11', '4', '10', '45', '24', '31', '47', '77', '22', '6', '20', '3', '18', '14', '5']
core           INFO 	Loading data for Singapore Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 16: Italian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['11', '16', '55', '4', '3', '18', '1', '5', '44', '10', '77', '20', '47', '63', '22', '31', '23', '14', '6', '24']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 17: Singapore Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '31', '44', '5', '14', '63', '6', '4', '3', '18', '22', '20', '77', '24', '47', '10', '55', '23']
core           INFO 	Loading data for United States Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 18: Japanese Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '16', '11', '63', '4', '14', '5', '20', '22', '31', '24', '23', '10', '47', '3', '6', '18', '77', '55']
core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 19: United States Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '11', '63', '55', '16', '3', '31', '4', '77', '10', '23', '24', '5', '18', '47', '20', '6', '14', '22']
core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 20: Mexico City Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['63', '44', '55', '16', '14', '1', '11', '31', '77', '18', '5', '24', '47', '10', '23', '6', '22', '4', '20', '3']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 21: São Paulo Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '55', '63', '4', '31', '18', '3', '5', '22', '24', '23', '10', '77', '47', '20', '44', '6', '14']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2022, 2022 Season Round 22: Abu Dhabi Grand Prix - Race done
********************
********************
2022 done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '55', '44', '18', '63', '77', '10', '23', '22', '2', '20', '21', '27', '24', '4', '31', '16', '81']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 1: Bahrain Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 11 completed the race distance 00:00.035000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['11', '1', '14', '63', '44', '55', '16', '31', '10', '20', '22', '27', '24', '21', '81', '2', '4', '77', '23', '18']
core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 2: Saudi Arabian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '14', '18', '11', '4', '27', '81', '24', '22', '77', '55', '10', '31', '21', '2', '20', '63', '23', '16']
core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 3: Australian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['11', '1', '16', '14', '55', '44', '18', '63', '4', '22', '81', '23', '20', '10', '31', '2', '27', '77', '24', '21']
core           INFO 	Loading data for Miami Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 4: Azerbaijan Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '63', '55', '44', '16', '10', '31', '20', '22', '18', '77', '23', '27', '24', '4', '21', '81', '2']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 5: Miami Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '14', '31', '44', '63', '16', '10', '55', '4', '81', '77', '21', '24', '23', '22', '11', '27', '2', '20', '18']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 6: Monaco Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 1 completed the race distance 00:00.037000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '63', '11', '55', '18', '14', '31', '24', '10', '16', '22', '81', '21', '27', '23', '4', '20', '77', '2']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 7: Spanish Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '22'
core           INFO 	Finished loading data for 20 drivers: ['1', '14', '44', '16', '55', '11', '23', '31', '18', '77', '81', '10', '4', '22', '27', '24', '20', '21', '63', '2']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 8: Canadian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '4', '14', '55', '63', '44', '18', '10', '23', '24', '2', '31', '77', '81', '21', '20', '22', '27']
core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 9: Austrian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '44', '81', '63', '11', '14', '23', '16', '55', '2', '77', '27', '18', '24', '22', '21', '10', '20', '31']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 10: British Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '11', '44', '81', '63', '16', '55', '14', '18', '23', '77', '3', '27', '22', '24', '20', '2', '31', '10']
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 11: Hungarian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '44', '14', '63', '4', '31', '18', '22', '10', '77', '24', '23', '20', '3', '2', '27', '55', '81']
core           INFO 	Loading data for Dutch Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 12: Belgian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 1 completed the race distance 00:02.059000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['1', '14', '10', '11', '55', '44', '4', '23', '81', '31', '18', '27', '40', '77', '22', '20', '63', '24', '16', '2']
core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 13: Dutch Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 22)
core        WARNING 	Driver 1 completed the race distance 06:25.888000 before the recorded end of the session.
core        WARNING 	Driver 11 completed the race distance 06:19.824000 before the recorded end of the session.
core        WARNING 	Driver 55 completed the race distance 06:14.695000 before the recorded end of the session.
core        WARNING 	Driver 16 completed the race distance 06:14.511000 before the recorded end of the session.
core        WARNING 	Driver 63 completed the race distance 06:07.860000 before the recorded end of the session.
core        WARNING 	Driver 44 completed the race distance 05:48.209000 before the recorded end of the session.
core        WARNING 	Driver 23 completed the race distance 05:40.782000 before the recorded end of the session.
core        WARNING 	Driver 4 completed the race distance 05:40.439000 before the recorded end of the session.
core        WARNING 	Driver 14 completed the race distance 05:39.594000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '44', '23', '4', '14', '77', '40', '81', '2', '24', '10', '18', '27', '20', '31', '22']
core           INFO 	Loading data for Singapore Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 14: Italian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 18)
core           INFO 	Finished loading data for 20 drivers: ['55', '4', '44', '16', '1', '10', '81', '11', '40', '20', '23', '24', '27', '2', '14', '63', '77', '31', '22', '18']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 15: Singapore Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 1 completed the race distance 00:00.076000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '44', '55', '63', '14', '31', '10', '40', '22', '24', '27', '20', '23', '2', '18', '11', '77']
core           INFO 	Loading data for Qatar Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 16: Japanese Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 55)
core           INFO 	Finished loading data for 20 drivers: ['1', '81', '4', '63', '16', '14', '31', '77', '24', '11', '18', '10', '23', '20', '22', '27', '40', '2', '44', '55']
core           INFO 	Loading data for United States Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 17: Qatar Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '55', '11', '63', '10', '18', '22', '23', '2', '27', '77', '24', '20', '3', '14', '81', '31', '44', '16']
core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 18: United States Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '16', '55', '4', '63', '3', '81', '23', '31', '10', '22', '27', '24', '77', '2', '18', '14', '20', '11']
core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 19: Mexico City Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 16)
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '14', '11', '18', '55', '10', '44', '22', '31', '2', '27', '3', '81', '63', '77', '24', '20', '23', '16']
core           INFO 	Loading data for Las Vegas Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 20: São Paulo Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 1 completed the race distance 00:00.001000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '31', '18', '55', '44', '63', '14', '81', '10', '23', '20', '3', '24', '2', '77', '22', '27', '4']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 21: Las Vegas Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '63', '11', '4', '81', '14', '22', '44', '18', '3', '31', '10', '23', '27', '2', '24', '55', '77', '20']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2023, 2023 Season Round 22: Abu Dhabi Grand Prix - Race done
********************
********************
2023 done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '4', '44', '81', '14', '18', '24', '20', '3', '22', '23', '27', '31', '10', '77', '2']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 1: Bahrain Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '81', '14', '63', '38', '4', '44', '27', '23', '20', '31', '2', '22', '3', '77', '24', '18', '10']
core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 2: Saudi Arabian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 19 drivers: ['55', '16', '4', '81', '11', '18', '22', '14', '27', '20', '23', '3', '10', '77', '24', '31', '63', '44', '1']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 3: Australian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '4', '14', '63', '81', '44', '22', '27', '18', '20', '77', '31', '10', '2', '24', '3', '23']
core           INFO 	Loading data for Chinese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 4: Japanese Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 1 completed the race distance 00:08.313000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '11', '16', '55', '63', '14', '81', '44', '27', '31', '23', '10', '24', '18', '20', '2', '3', '22', '77']
core           INFO 	Loading data for Miami Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 5: Chinese Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '16', '11', '55', '44', '22', '63', '14', '31', '27', '10', '81', '24', '3', '77', '18', '23', '20', '2']
core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 6: Miami Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '16', '81', '55', '44', '63', '11', '18', '22', '27', '20', '3', '31', '24', '10', '2', '77', '14', '23']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 7: Emilia Romagna Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['16', '81', '55', '4', '63', '1', '44', '22', '23', '10', '14', '3', '77', '18', '2', '24', '31', '11', '27', '20']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 8: Monaco Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '63', '44', '81', '14', '18', '3', '10', '31', '27', '20', '77', '22', '24', '55', '23', '11', '16', '2']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 9: Canadian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 1 completed the race distance 00:00.015000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '44', '63', '16', '55', '81', '11', '10', '31', '27', '14', '24', '18', '3', '77', '20', '23', '22', '2']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 10: Spanish Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['63', '81', '55', '44', '1', '27', '11', '20', '3', '10', '16', '31', '18', '22', '23', '77', '24', '14', '2', '4']
core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 11: Austrian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 10)
core           INFO 	Finished loading data for 20 drivers: ['44', '1', '4', '81', '55', '27', '18', '14', '23', '22', '2', '20', '3', '16', '77', '31', '11', '24', '63', '10']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 12: British Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '44', '16', '1', '55', '11', '63', '22', '18', '14', '3', '27', '23', '20', '77', '2', '31', '24', '10']
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 13: Hungarian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '14'
core        WARNING 	Fixed incorrect tyre stint information for driver '3'
core        WARNING 	Fixed incorrect tyre stint information for driver '18'
core        WARNING 	Fixed incorrect tyre stint information for driver '22'
core           INFO 	Finished loading data for 20 drivers: ['44', '81', '16', '1', '4', '55', '11', '14', '31', '3', '18', '23', '10', '20', '77', '22', '2', '27', '24', '63']
core           INFO 	Loading data for Dutch Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 14: Belgian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '16', '81', '55', '11', '63', '44', '10', '14', '27', '3', '18', '23', '31', '2', '22', '20', '77', '24']
core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 15: Dutch Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['16', '81', '4', '55', '44', '1', '63', '11', '23', '20', '14', '43', '3', '31', '10', '77', '27', '24', '18', '22']
core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 16: Italian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['81', '16', '63', '4', '1', '14', '23', '43', '44', '50', '27', '10', '3', '24', '31', '77', '11', '55', '18', '22']
core           INFO 	Loading data for Singapore Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 17: Azerbaijan Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '81', '63', '16', '44', '55', '14', '27', '11', '43', '22', '31', '18', '24', '77', '10', '3', '20', '23']
core           INFO 	Loading data for United States Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 18: Singapore Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['16', '55', '1', '4', '81', '63', '11', '27', '30', '43', '20', '10', '14', '22', '18', '23', '77', '31', '24', '44']
core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 19: United States Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['55', '4', '16', '44', '63', '1', '20', '81', '27', '10', '18', '43', '31', '77', '24', '30', '11', '14', '23', '22']
core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 20: Mexico City Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 23)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 18)
core           INFO 	Finished loading data for 20 drivers: ['1', '31', '10', '63', '16', '4', '22', '81', '30', '44', '11', '50', '77', '14', '24', '55', '43', '23', '18', '27']
core           INFO 	Loading data for Las Vegas Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 21: São Paulo Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 63: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver 44: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 55: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 16: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver  1: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver  4: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 81: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 30: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver 77: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver 63 completed the race distance 00:00.427000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['63', '44', '55', '16', '1', '4', '81', '27', '22', '11', '14', '20', '24', '43', '18', '30', '31', '77', '23', '10']
core           INFO 	Loading data for Qatar Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 22: Las Vegas Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '43'
core        WARNING 	Fixed incorrect tyre stint information for driver '31'
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '81', '63', '10', '55', '14', '24', '20', '4', '77', '44', '22', '30', '23', '27', '11', '18', '43', '31']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 23: Qatar Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['4', '55', '16', '44', '63', '1', '10', '27', '14', '81', '23', '22', '24', '18', '61', '20', '30', '77', '43', '11']
core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2024, 2024 Season Round 24: Abu Dhabi Grand Prix - Race done
********************
********************
2024 done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '87'
core        WARNING 	Fixed incorrect tyre stint information for driver '30'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
core        WARNING 	Driver 4 completed the race distance 00:00.022000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '63', '12', '23', '18', '27', '16', '81', '44', '10', '22', '31', '87', '30', '5', '14', '55', '7', '6']
core           INFO 	Loading data for Chinese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2025, 2025 Season Round 1: Australian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '63', '1', '31', '12', '23', '87', '18', '55', '6', '30', '7', '5', '27', '22', '14', '16', '44', '10']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2025, 2025 Season Round 2: Chinese Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '12', '44', '6', '23', '87', '14', '22', '10', '55', '7', '27', '30', '31', '5', '18']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2025, 2025 Season Round 3: Japanese Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['81', '63', '4', '16', '44', '1', '10', '31', '22', '87', '12', '23', '6', '7', '14', '30', '18', '5', '55', '27']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2025, 2025 Season Round 4: Bahrain Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['81', '1', '16', '4', '63', '12', '44', '55', '23', '6', '14', '30', '87', '31', '27', '18', '7', '5', '22', '10']
core           INFO 	Loading data for Miami Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

********************
2025, 2025 Season Round 5: Saudi Arabian Grand Prix - Race done
********************

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
Request for URL https://api.jolpi.ca/ergast/f1/2025/6/laps/1.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
core        WARNING 	Driver 81 completed the race distance 00:00.036000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '63', '1', '23', '12', '16', '44', '55', '22', '6', '31', '10', '27', '14', '18', '30', '5', '87', '7']
core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2025/7/results.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

********************
2025, 2025 Season Round 6: Miami Grand Prix - Race done
********************

Request for URL https://api.jolpi.ca/ergast/f1/2025/7/laps/1.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '44', '23', '16', '63', '55', '6', '22', '14', '27', '10', '30', '18', '43', '87', '5', '12', '31']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2025/8/results.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

********************
2025, 2025 Season Round 7: Emilia Romagna Grand Prix - Race done
********************

Request for URL https://api.jolpi.ca/ergast/f1/2025/8/laps/1.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
core           INFO 	Finished loading data for 20 drivers: ['4', '16', '81', '1', '44', '6', '31', '30', '23', '55', '63', '87', '43', '5', '18', '27', '22', '12', '14', '10']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2025/9/results.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

********************
2025, 2025 Season Round 8: Monaco Grand Prix - Race done
********************

Request for URL https://api.jolpi.ca/ergast/f1/2025/9/laps/1.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
core           INFO 	Finished loading data for 19 drivers: ['81', '4', '16', '63', '27', '44', '6', '10', '14', '1', '30', '5', '22', '55', '43', '31', '87', '12', '23']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2025/10/results.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

********************
2025, 2025 Season Round 9: Spanish Grand Prix - Race done
********************

Request for URL https://api.jolpi.ca/ergast/f1/2025/10/laps/1.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
core           INFO 	Finished loading data for 20 drivers: ['63', '1', '12', '81', '16', '44', '14', '27', '31', '55', '87', '22', '43', '5', '10', '6', '18', '4', '30', '23']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2025/11/results.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

********************
2025, 2025 Season Round 10: Canadian Grand Prix - Race done
********************

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 55)
Request for URL https://api.jolpi.ca/ergast/f1/2025/11/laps/1.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '16', '44', '63', '30', '14', '5', '27', '31', '87', '6', '10', '18', '43', '22', '23', '1', '12', '55']
core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2025/12/results.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

********************
2025, 2025 Season Round 11: Austrian Grand Prix - Race done
********************

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 43)
Request for URL https://api.jolpi.ca/ergast/f1/2025/12/laps/1.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '27', '44', '1', '10', '18', '23', '14', '63', '87', '55', '31', '16', '22', '12', '6', '5', '30', '43']
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2025/13/results.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '81'

********************
2025, 2025 Season Round 12: British Grand Prix - Race done
********************

core        WARNING 	Fixed incorrect tyre stint information for driver '4'
core        WARNING 	Fixed incorrect tyre stint information for driver '16'
core        WARNING 	Fixed incorrect tyre stint information for driver '1'
core        WARNING 	Fixed incorrect tyre stint information for driver '63'
core        WARNING 	Fixed incorrect tyre stint information for driver '23'
core        WARNING 	Fixed incorrect tyre stint information for driver '44'
core        WARNING 	Fixed incorrect tyre stint information for driver '30'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
core        WARNING 	Fixed incorrect tyre stint information for driver '10'
core        WARNING 	Fixed incorrect tyre stint information for driver '87'
core        WARNING 	Fixed incorrect tyre stint information for driver '27'
core        WARNING 	Fixed incorrect tyre stint information for driver '22'
core        WARNING 	Fixed incorrect tyre stint information for driver '18'
core        WARNING 	Fixed incorrect tyre stint information for driver '31'
core        WARNING 	Fixed incorrect tyre stint information for driver '12'
core        WARNING 	Fixed incorrect tyre stint information for driver '14'
core        WARNING 	Fixed incorrect tyre stint information for driver '55'
core        WARNING 	Fixed incorrect tyre stint information for driver '43'
core        WARNING 	Fixed incorrect tyre stint information for driver '6'
Request for URL https://api.jolpi.ca/ergast/f1/2025/13/laps/1.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '16', '1', '63', '23', '44', '30', '5', '10', '87', '27', '22', '18', '31', '12', '14', '55', '43', '6']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2025/14/results.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

********************
2025, 2025 Season Round 13: Belgian Grand Prix - Race done
********************

Request for URL https://api.jolpi.ca/ergast/f1/2025/14/laps/1.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '63', '16', '14', '5', '18', '30', '1', '12', '6', '44', '27', '55', '23', '31', '22', '43', '10', '87']
core           INFO 	Loading data for Dutch Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2025/15/results.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

********************
2025, 2025 Season Round 14: Hungarian Grand Prix - Race done
********************

Request for URL https://api.jolpi.ca/ergast/f1/2025/15/laps/1.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
core           INFO 	Finished loading data for 20 drivers: ['81', '1', '6', '63', '23', '87', '18', '14', '22', '31', '43', '30', '55', '27', '5', '12', '10', '4', '16', '44']
core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2025/16/results.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

********************
2025, 2025 Season Round 15: Dutch Grand Prix - Race done
********************

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 27)
Request for URL https://api.jolpi.ca/ergast/f1/2025/16/laps/1.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '44', '23', '5', '12', '6', '55', '87', '22', '30', '31', '10', '43', '18', '14', '27']
core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2025/17/results.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

********************
2025, 2025 Season Round 16: Italian Grand Prix - Race done
********************

Request for URL https://api.jolpi.ca/ergast/f1/2025/17/laps/1.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
core        WARNING 	Driver 1 completed the race distance 00:00.015000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['1', '63', '55', '12', '30', '22', '4', '44', '16', '6', '5', '87', '23', '31', '14', '27', '18', '10', '43', '81']
core           INFO 	Loading data for Singapore Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2025/18/results.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

********************
2025, 2025 Season Round 17: Azerbaijan Grand Prix - Race done
********************

Request for URL https://api.jolpi.ca/ergast/f1/2025/18/laps/1.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
core           INFO 	Finished loading data for 20 drivers: ['63', '1', '4', '81', '12', '16', '14', '44', '87', '55', '6', '22', '18', '23', '30', '43', '5', '31', '10', '27']
core           INFO 	Loading data for United States Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2025/19/results.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

********************
2025, 2025 Season Round 18: Singapore Grand Prix - Race done
********************

Request for URL https://api.jolpi.ca/ergast/f1/2025/19/laps/1.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '16', '44', '81', '63', '22', '27', '87', '14', '30', '18', '12', '23', '31', '6', '43', '5', '10', '55']
core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2025/20/results.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

********************
2025, 2025 Season Round 19: United States Grand Prix - Race done
********************

Request for URL https://api.jolpi.ca/ergast/f1/2025/20/laps/1.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
core           INFO 	Finished loading data for 20 drivers: ['4', '16', '1', '87', '81', '12', '63', '44', '31', '5', '22', '23', '6', '18', '10', '43', '55', '14', '27', '30']
core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2025/21/results.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

********************
2025, 2025 Season Round 20: Mexico City Grand Prix - Race done
********************

Request for URL https://api.jolpi.ca/ergast/f1/2025/21/laps/1.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
core        WARNING 	Driver 4 completed the race distance 00:00.010000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['4', '12', '1', '63', '81', '87', '30', '6', '27', '10', '23', '31', '55', '14', '43', '18', '22', '44', '16', '5']
core           INFO 	Loading data for Las Vegas Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2025/22/results.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

********************
2025, 2025 Season Round 21: São Paulo Grand Prix - Race done
********************

core        WARNING 	Fixed incorrect tyre stint information for driver '63'
Request for URL https://api.jolpi.ca/ergast/f1/2025/22/laps/1.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
core           INFO 	Finished loading data for 20 drivers: ['1', '63', '12', '16', '55', '6', '27', '44', '31', '87', '14', '22', '10', '30', '43', '23', '5', '18', '4', '81']
core           INFO 	Loading data for Qatar Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2025/23/results.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

********************
2025, 2025 Season Round 22: Las Vegas Grand Prix - Race done
********************

Request for URL https://api.jolpi.ca/ergast/f1/2025/23/laps/1.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
core           INFO 	Finished loading data for 20 drivers: ['1', '81', '55', '4', '12', '63', '14', '16', '30', '22', '23', '44', '5', '43', '31', '10', '18', '6', '87', '27']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2025/24/results.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

********************
2025, 2025 Season Round 23: Qatar Grand Prix - Race done
********************

Request for URL https://api.jolpi.ca/ergast/f1/2025/24/laps/1.json failed; using cached response
Traceback (most recent call last):
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 110, in send
    lim.limit()
  File "/home/archit/Documents/chaiAurCode/100DaysOfMl/Projects/theF1Project/.venv/lib/python3.12/site-packages/fastf1/req.py", line 80, in limit
    raise RateLimitExceededError(self._info)
fastf1.exceptions.RateLimitExceededError: any API: 500 calls/h
core           INFO 	Finished loading data for 20 drivers: ['1', '81', '4', '16', '63', '14', '31', '44', '27', '18', '5', '87', '55', '22', '12', '23', '6', '30', '10', '43']

********************
2025, 2025 Season Round 24: Abu Dhabi Grand Prix - Race done
********************
********************
2025 done
********************

# dataset altering

In [17]:
highErr=list()
flag =0
for key, value in sessions.items():
    
    i=1
    for k in value:
        print("_"*20)
        print(f"{key}, {k}")
        print("_"*20)
        print(k.laps["IsAccurate"].mean(), end="\n\n")
        if k.laps["IsAccurate"].mean()<0.75:
            highErr.append(k)

print(flag)
print(highErr, len(highErr))

____________________
2020, 2020 Season Round 1: Austrian Grand Prix - Race
____________________
0.651272384542884

____________________
2020, 2020 Season Round 2: Styrian Grand Prix - Race
____________________
0.9168026101141925

____________________
2020, 2020 Season Round 3: Hungarian Grand Prix - Race
____________________
0.9178598342125094

____________________
2020, 2020 Season Round 4: British Grand Prix - Race
____________________
0.750278706800446

____________________
2020, 2020 Season Round 5: 70th Anniversary Grand Prix - Race
____________________
0.8995121951219512

____________________
2020, 2020 Season Round 6: Spanish Grand Prix - Race
____________________
0.9285714285714286

____________________
2020, 2020 Season Round 7: Belgian Grand Prix - Race
____________________
0.8541666666666666

____________________
2020, 2020 Season Round 8: Italian Grand Prix - Race
____________________
0.8196544276457883

____________________
2020, 2020 Season Round 9: Tuscan Grand Prix - Race
____________________
0.7061068702290076

____________________
2020, 2020 Season Round 10: Russian Grand Prix - Race
____________________
0.8375527426160337

____________________
2020, 2020 Season Round 11: Eifel Grand Prix - Race
____________________
0.8204121687929342

____________________
2020, 2020 Season Round 12: Portuguese Grand Prix - Race
____________________
0.9456521739130435

____________________
2020, 2020 Season Round 13: Emilia Romagna Grand Prix - Race
____________________
0.8205128205128205

____________________
2020, 2020 Season Round 14: Turkish Grand Prix - Race
____________________
0.8672237697307336

____________________
2020, 2020 Season Round 15: Bahrain Grand Prix - Race
____________________
0.7212953876349362

____________________
2020, 2020 Season Round 16: Sakhir Grand Prix - Race
____________________
0.7868318122555411

____________________
2020, 2020 Season Round 17: Abu Dhabi Grand Prix - Race
____________________
0.8860153256704981

____________________
2021, 2021 Season Round 1: Bahrain Grand Prix - Race
____________________
0.8296007789678675

____________________
2021, 2021 Season Round 2: Emilia Romagna Grand Prix - Race
____________________
0.7923691215616682

____________________
2021, 2021 Season Round 3: Portuguese Grand Prix - Race
____________________
0.8714859437751004

____________________
2021, 2021 Season Round 4: Spanish Grand Prix - Race
____________________
0.8829190056134724

____________________
2021, 2021 Season Round 5: Monaco Grand Prix - Race
____________________
0.9591261451726568

____________________
2021, 2021 Season Round 6: Azerbaijan Grand Prix - Race
____________________
0.7688229056203606

____________________
2021, 2021 Season Round 7: French Grand Prix - Race
____________________
0.9391056137012369

____________________
2021, 2021 Season Round 8: Styrian Grand Prix - Race
____________________
0.9452160493827161

____________________
2021, 2021 Season Round 9: Austrian Grand Prix - Race
____________________
0.9170403587443946

____________________
2021, 2021 Season Round 10: British Grand Prix - Race
____________________
0.8876288659793814

____________________
2021, 2021 Season Round 11: Hungarian Grand Prix - Race
____________________
0.8944162436548223

____________________
2021, 2021 Season Round 12: Belgian Grand Prix - Race
____________________
0.0

____________________
2021, 2021 Season Round 13: Dutch Grand Prix - Race
____________________
0.9412196914033799

____________________
2021, 2021 Season Round 14: Italian Grand Prix - Race
____________________
0.8305274971941639

____________________
2021, 2021 Season Round 15: Russian Grand Prix - Race
____________________
0.9024390243902439

____________________
2021, 2021 Season Round 16: Turkish Grand Prix - Race
____________________
0.948561464690497

____________________
2021, 2021 Season Round 17: United States Grand Prix - Race
____________________
0.8793103448275862

____________________
2021, 2021 Season Round 18: Mexico City Grand Prix - Race
____________________
0.9048374306106265

____________________
2021, 2021 Season Round 19: São Paulo Grand Prix - Race
____________________
0.8176470588235294

____________________
2021, 2021 Season Round 20: Qatar Grand Prix - Race
____________________
0.8859964093357271

____________________
2021, 2021 Season Round 21: Saudi Arabian Grand Prix - Race
____________________
0.6236686390532544

____________________
2021, 2021 Season Round 22: Abu Dhabi Grand Prix - Race
____________________
0.818

____________________
2022, 2022 Season Round 1: Bahrain Grand Prix - Race
____________________
0.7937777777777778

____________________
2022, 2022 Season Round 2: Saudi Arabian Grand Prix - Race
____________________
0.7939024390243903

____________________
2022, 2022 Season Round 3: Australian Grand Prix - Race
____________________
0.7779904306220096

____________________
2022, 2022 Season Round 4: Emilia Romagna Grand Prix - Race
____________________
0.8886925795053003

____________________
2022, 2022 Season Round 5: Miami Grand Prix - Race
____________________
0.8306527909176916

____________________
2022, 2022 Season Round 6: Spanish Grand Prix - Race
____________________
0.8975609756097561

____________________
2022, 2022 Season Round 7: Monaco Grand Prix - Race
____________________
0.820186598812553

____________________
2022, 2022 Season Round 8: Azerbaijan Grand Prix - Race
____________________
0.8574635241301908

____________________
2022, 2022 Season Round 9: Canadian Grand Prix - Race
____________________
0.8140822784810127

____________________
2022, 2022 Season Round 10: British Grand Prix - Race
____________________
0.8269938650306748

____________________
2022, 2022 Season Round 11: Austrian Grand Prix - Race
____________________
0.8919939577039275

____________________
2022, 2022 Season Round 12: French Grand Prix - Race
____________________
0.8695198329853863

____________________
2022, 2022 Season Round 13: Hungarian Grand Prix - Race
____________________
0.8698481561822126

____________________
2022, 2022 Season Round 14: Belgian Grand Prix - Race
____________________
0.8143939393939394

____________________
2022, 2022 Season Round 15: Dutch Grand Prix - Race
____________________
0.8182471264367817

____________________
2022, 2022 Season Round 16: Italian Grand Prix - Race
____________________
0.8012358393408857

____________________
2022, 2022 Season Round 17: Singapore Grand Prix - Race
____________________
0.7153439153439154

____________________
2022, 2022 Season Round 18: Japanese Grand Prix - Race
____________________
0.7297830374753451

____________________
2022, 2022 Season Round 19: United States Grand Prix - Race
____________________
0.7842741935483871

____________________
2022, 2022 Season Round 20: Mexico City Grand Prix - Race
____________________
0.9311094996374184

____________________
2022, 2022 Season Round 21: São Paulo Grand Prix - Race
____________________
0.7474185861795075

____________________
2022, 2022 Season Round 22: Abu Dhabi Grand Prix - Race
____________________
0.9239033124440466

____________________
2023, 2023 Season Round 1: Bahrain Grand Prix - Race
____________________
0.865530303030303

____________________
2023, 2023 Season Round 2: Saudi Arabian Grand Prix - Race
____________________
0.8791092258748674

____________________
2023, 2023 Season Round 3: Australian Grand Prix - Race
____________________
0.7666999002991027

____________________
2023, 2023 Season Round 4: Azerbaijan Grand Prix - Race
____________________
0.8794178794178794

____________________
2023, 2023 Season Round 5: Miami Grand Prix - Race
____________________
0.9472759226713533

____________________
2023, 2023 Season Round 6: Monaco Grand Prix - Race
____________________
0.9392739273927393

____________________
2023, 2023 Season Round 7: Spanish Grand Prix - Race
____________________
0.9199695121951219

____________________
2023, 2023 Season Round 8: Canadian Grand Prix - Race
____________________
0.8557327258921792

____________________
2023, 2023 Season Round 9: Austrian Grand Prix - Race
____________________
0.8759231905465288

____________________
2023, 2023 Season Round 10: British Grand Prix - Race
____________________
0.8259526261585994

____________________
2023, 2023 Season Round 11: Hungarian Grand Prix - Race
____________________
0.9249201277955271

____________________
2023, 2023 Season Round 12: Belgian Grand Prix - Race
____________________
0.883578431372549

____________________
2023, 2023 Season Round 13: Dutch Grand Prix - Race
____________________
0.7550260610573343

____________________
2023, 2023 Season Round 14: Italian Grand Prix - Race
____________________
0.9174503657262278

____________________
2023, 2023 Season Round 15: Singapore Grand Prix - Race
____________________
0.8805147058823529

____________________
2023, 2023 Season Round 16: Japanese Grand Prix - Race
____________________
0.7977272727272727

____________________
2023, 2023 Season Round 17: Qatar Grand Prix - Race
____________________
0.8290258449304175

____________________
2023, 2023 Season Round 18: United States Grand Prix - Race
____________________
0.9063116370808678

____________________
2023, 2023 Season Round 19: Mexico City Grand Prix - Race
____________________
0.8822152886115444

____________________
2023, 2023 Season Round 20: São Paulo Grand Prix - Race
____________________
0.8898916967509025

____________________
2023, 2023 Season Round 21: Las Vegas Grand Prix - Race
____________________
0.7801268498942917

____________________
2023, 2023 Season Round 22: Abu Dhabi Grand Prix - Race
____________________
0.9187554019014693

____________________
2024, 2024 Season Round 1: Bahrain Grand Prix - Race
____________________
0.9069973427812223

____________________
2024, 2024 Season Round 2: Saudi Arabian Grand Prix - Race
____________________
0.9056603773584906

____________________
2024, 2024 Season Round 3: Australian Grand Prix - Race
____________________
0.8587174348697395

____________________
2024, 2024 Season Round 4: Japanese Grand Prix - Race
____________________
0.8654906284454245

____________________
2024, 2024 Season Round 5: Chinese Grand Prix - Race
____________________
0.7383720930232558

____________________
2024, 2024 Season Round 6: Miami Grand Prix - Race
____________________
0.8406840684068407

____________________
2024, 2024 Season Round 7: Emilia Romagna Grand Prix - Race
____________________
0.9402261712439418

____________________
2024, 2024 Season Round 8: Monaco Grand Prix - Race
____________________
0.9595796281325788

____________________
2024, 2024 Season Round 9: Canadian Grand Prix - Race
____________________
0.8034591194968553

____________________
2024, 2024 Season Round 10: Spanish Grand Prix - Race
____________________
0.9206106870229007

____________________
2024, 2024 Season Round 11: Austrian Grand Prix - Race
____________________
0.903202846975089

____________________
2024, 2024 Season Round 12: British Grand Prix - Race
____________________
0.8854166666666666

____________________
2024, 2024 Season Round 13: Hungarian Grand Prix - Race
____________________
0.9254612546125461

____________________
2024, 2024 Season Round 14: Belgian Grand Prix - Race
____________________
0.8929845422116528

____________________
2024, 2024 Season Round 15: Dutch Grand Prix - Race
____________________
0.9495091164095372

____________________
2024, 2024 Season Round 16: Italian Grand Prix - Race
____________________
0.9196428571428571

____________________
2024, 2024 Season Round 17: Azerbaijan Grand Prix - Race
____________________
0.9054470709146968

____________________
2024, 2024 Season Round 18: Singapore Grand Prix - Race
____________________
0.9422259983007647

____________________
2024, 2024 Season Round 19: United States Grand Prix - Race
____________________
0.8847969782813976

____________________
2024, 2024 Season Round 20: Mexico City Grand Prix - Race
____________________
0.8732510288065843

____________________
2024, 2024 Season Round 21: São Paulo Grand Prix - Race
____________________
0.8315696649029982

____________________
2024, 2024 Season Round 22: Las Vegas Grand Prix - Race
____________________
0.8805970149253731

____________________
2024, 2024 Season Round 23: Qatar Grand Prix - Race
____________________
0.76033934252386

____________________
2024, 2024 Season Round 24: Abu Dhabi Grand Prix - Race
____________________
0.8898550724637682

____________________
2025, 2025 Season Round 1: Australian Grand Prix - Race
____________________
0.6127292340884574

____________________
2025, 2025 Season Round 2: Chinese Grand Prix - Race
____________________
0.9342723004694836

____________________
2025, 2025 Season Round 3: Japanese Grand Prix - Race
____________________
0.9414542020774316

____________________
2025, 2025 Season Round 4: Bahrain Grand Prix - Race
____________________
0.8439716312056738

____________________
2025, 2025 Season Round 5: Saudi Arabian Grand Prix - Race
____________________
0.9020044543429844

____________________
2025, 2025 Season Round 6: Miami Grand Prix - Race
____________________
0.8567164179104477

____________________
2025, 2025 Season Round 7: Emilia Romagna Grand Prix - Race
____________________
0.792046396023198

____________________
2025, 2025 Season Round 8: Monaco Grand Prix - Race
____________________
0.8919298245614035

____________________
2025, 2025 Season Round 9: Spanish Grand Prix - Race
____________________
0.8229426433915212

____________________
2025, 2025 Season Round 10: Canadian Grand Prix - Race
____________________
0.8873239436619719

____________________
2025, 2025 Season Round 11: Austrian Grand Prix - Race
____________________
0.8969804618117229

____________________
2025, 2025 Season Round 12: British Grand Prix - Race
____________________
0.6012121212121212

____________________
2025, 2025 Season Round 13: Belgian Grand Prix - Race
____________________
0.8498293515358362

____________________
2025, 2025 Season Round 14: Hungarian Grand Prix - Race
____________________
0.9422514619883041

____________________
2025, 2025 Season Round 15: Dutch Grand Prix - Race
____________________
0.7631964809384164

____________________
2025, 2025 Season Round 16: Italian Grand Prix - Race
____________________
0.9404517453798767

____________________
2025, 2025 Season Round 17: Azerbaijan Grand Prix - Race
____________________
0.8832644628099173

____________________
2025, 2025 Season Round 18: Singapore Grand Prix - Race
____________________
0.9462978030919447

____________________
2025, 2025 Season Round 19: United States Grand Prix - Race
____________________
0.9025304592314901

____________________
2025, 2025 Season Round 20: Mexico City Grand Prix - Race
____________________
0.9129057798891528

____________________
2025, 2025 Season Round 21: São Paulo Grand Prix - Race
____________________
0.8385291766586731

____________________
2025, 2025 Season Round 22: Las Vegas Grand Prix - Race
____________________
0.8577878103837472

____________________
2025, 2025 Season Round 23: Qatar Grand Prix - Race
____________________
0.8641049671977507

____________________
2025, 2025 Season Round 24: Abu Dhabi Grand Prix - Race
____________________
0.9359861591695502

0
[2020 Season Round 1: Austrian Grand Prix - Race, 2020 Season Round 9: Tuscan Grand Prix - Race, 2020 Season Round 15: Bahrain Grand Prix - Race, 2021 Season Round 12: Belgian Grand Prix - Race, 2021 Season Round 21: Saudi Arabian Grand Prix - Race, 2022 Season Round 17: Singapore Grand Prix - Race, 2022 Season Round 18: Japanese Grand Prix - Race, 2022 Season Round 21: São Paulo Grand Prix - Race, 2024 Season Round 5: Chinese Grand Prix - Race, 2025 Season Round 1: Australian Grand Prix - Race, 2025 Season Round 12: British Grand Prix - Race] 11

In [18]:
sessions[2024][20].laps.columns

Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'FastF1Generated', 'IsAccurate'],
      dtype='object')

In [19]:
sessions[2024][20].laps.describe()

,Time,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,TyreLife,LapStartTime,LapStartDate,Position
count,1134,1097,1134.000000,1134.000000,35,36,1098,1133,1133,1096,1133,1133,1133.000000,1133.000000,1097.000000,1129.000000,1134.000000,1134,0,1133.000000
mean,0 days 02:14:29.033150793,0 days 00:01:29.047629899,33.452381,1.993827,0 days 02:06:33.511942857,0 days 01:56:56.890805555,0 days 00:00:23.134932604,0 days 00:00:47.007007943,0 days 00:00:20.487070609,0 days 02:14:05.985776459,0 days 02:14:07.389924095,0 days 02:14:27.879741394,282.460724,207.906443,295.322698,240.990257,17.302469,0 days 02:12:56.450295414,NaT,8.771403
min,0 days 01:13:25.562000,0 days 00:01:20.472000,1.000000,1.000000,0 days 01:12:09.688000,0 days 01:46:04.229000,0 days 00:00:20.546000,0 days 00:00:42.236000,0 days 00:00:17.690000,0 days 01:13:47.169000,0 days 01:13:07.092000,0 days 01:13:25.744000,96.000000,68.000000,133.000000,79.000000,1.000000,0 days 01:11:54.770000,NaT,1.000000
25%,0 days 01:35:07.312500,0 days 00:01:23.701000,16.000000,1.000000,0 days 01:51:27.785500,0 days 01:51:23.093750,0 days 00:00:21.341250,0 days 00:00:44.165000,0 days 00:00:18.116000,0 days 01:35:09.107000,0 days 01:34:48.638000,0 days 01:35:07.183000,291.000000,208.000000,299.000000,235.000000,8.000000,0 days 01:33:41.704750,NaT,5.000000
50%,0 days 02:01:14.570500,0 days 00:01:24.874000,32.000000,2.000000,0 days 01:58:44.080000,0 days 01:59:25.408500,0 days 00:00:21.617000,0 days 00:00:44.958000,0 days 00:00:18.316000,0 days 01:59:11.468000,0 days 02:00:09.161000,0 days 02:01:13.091000,298.000000,218.000000,304.000000,250.000000,17.000000,0 days 01:58:36.679000,NaT,9.000000
75%,0 days 02:54:26.585250,0 days 00:01:26.915000,51.000000,3.000000,0 days 02:24:35.072000,0 days 02:00:56.842250,0 days 00:00:22.176500,0 days 00:00:46.237000,0 days 00:00:18.697000,0 days 02:53:43.091500,0 days 02:54:10.067000,0 days 02:54:28.280000,302.000000,225.000000,307.000000,260.000000,25.000000,0 days 02:53:03.633500,NaT,13.000000
max,0 days 03:20:09.121000,0 days 00:02:23.552000,69.000000,5.000000,0 days 02:25:01.911000,0 days 02:23:53.295000,0 days 00:01:32.763000,0 days 00:01:15.860000,0 days 00:01:04.005000,0 days 03:19:06.894000,0 days 03:19:50.905000,0 days 03:20:09.129000,312.000000,240.000000,316.000000,294.000000,41.000000,0 days 03:18:45.420000,NaT,18.000000
std,0 days 00:41:40.833764199,0 days 00:00:11.383902130,19.903982,1.040638,0 days 00:18:56.338162020,0 days 00:06:49.200022685,0 days 00:00:04.982124406,0 days 00:00:05.710201957,0 days 00:00:06.487736792,0 days 00:41:35.241529752,0 days 00:41:41.726956546,0 days 00:41:41.619379269,39.337238,30.727890,27.300500,31.647198,10.200430,0 days 00:41:42.080448704,NaN,4.839089

In [20]:
sessions[2024][20].laps.info()

<class 'fastf1.core.Laps'>
RangeIndex: 1134 entries, 0 to 1133
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Time                1134 non-null   timedelta64[ns]
 1   Driver              1134 non-null   object
 2   DriverNumber        1134 non-null   object
 3   LapTime             1097 non-null   timedelta64[ns]
 4   LapNumber           1134 non-null   float64
 5   Stint               1134 non-null   float64
 6   PitOutTime          35 non-null     timedelta64[ns]
 7   PitInTime           36 non-null     timedelta64[ns]
 8   Sector1Time         1098 non-null   timedelta64[ns]
 9   Sector2Time         1133 non-null   timedelta64[ns]
 10  Sector3Time         1133 non-null   timedelta64[ns]
 11  Sector1SessionTime  1096 non-null   timedelta64[ns]
 12  Sector2SessionTime  1133 non-null   timedelta64[ns]
 13  Sector3SessionTime  1133 non-null   timedelta64[ns]
 14  SpeedI1             1133 non-null   float64
 15  SpeedI2             1133 non-null   float64
 16  SpeedFL             1097 non-null   float64
 17  SpeedST             1129 non-null   float64
 18  IsPersonalBest      1133 non-null   object
 19  Compound            1134 non-null   object
 20  TyreLife            1134 non-null   float64
 21  FreshTyre           1134 non-null   bool
 22  Team                1134 non-null   object
 23  LapStartTime        1134 non-null   timedelta64[ns]
 24  LapStartDate        0 non-null      datetime64[ns]
 25  TrackStatus         1134 non-null   object
 26  Position            1133 non-null   float64
 27  Deleted             0 non-null      object
 28  DeletedReason       1133 non-null   object
 29  FastF1Generated     1134 non-null   bool
 30  IsAccurate          1134 non-null   bool
dtypes: bool(3), datetime64[ns](1), float64(8), object(8), timedelta64[ns](11)
memory usage: 251.5+ KB

In [21]:
sessions[2024][20].laps[sessions[2024][20].laps['DriverNumber']=="44"][['Time', 'Driver', 'LapTime', 'LapNumber', 'Compound', 'TyreLife', 'Team', 'IsAccurate', 'Position', 'TrackStatus']].iloc[20:50]

,Time,Driver,LapTime,LapNumber,Compound,TyreLife,Team,IsAccurate,Position,TrackStatus
770,0 days 01:42:12.680000,HAM,0 days 00:01:24.385000,21.0,INTERMEDIATE,21.0,Mercedes,True,15.0,1
771,0 days 01:43:37.186000,HAM,0 days 00:01:24.506000,22.0,INTERMEDIATE,22.0,Mercedes,True,14.0,1
772,0 days 01:45:01.741000,HAM,0 days 00:01:24.555000,23.0,INTERMEDIATE,23.0,Mercedes,True,13.0,1
773,0 days 01:46:25.714000,HAM,0 days 00:01:23.973000,24.0,INTERMEDIATE,24.0,Mercedes,True,13.0,1
774,0 days 01:47:50.879000,HAM,0 days 00:01:25.165000,25.0,INTERMEDIATE,25.0,Mercedes,True,12.0,12
775,0 days 01:49:15.862000,HAM,0 days 00:01:24.983000,26.0,INTERMEDIATE,26.0,Mercedes,True,11.0,1
776,0 days 01:50:55.929000,HAM,0 days 00:01:40.067000,27.0,INTERMEDIATE,27.0,Mercedes,False,12.0,126
777,0 days 01:52:55.767000,HAM,0 days 00:01:59.838000,28.0,INTERMEDIATE,1.0,Mercedes,False,12.0,671
778,0 days 01:54:41.083000,HAM,0 days 00:01:45.316000,29.0,INTERMEDIATE,2.0,Mercedes,True,10.0,1
779,0 days 01:56:37.087000,HAM,0 days 00:01:56.004000,30.0,INTERMEDIATE,3.0,Mercedes,False,11.0,14
780,0 days 01:58:29.118000,HAM,0 days 00:01:52.031000,31.0,INTERMEDIATE,4.0,Mercedes,False,11.0,4
781,0 days 02:01:10.205000,HAM,NaT,32.0,INTERMEDIATE,5.0,Mercedes,False,11.0,45
782,0 days 02:26:42.548000,HAM,NaT,33.0,INTERMEDIATE,1.0,Mercedes,False,11.0,12
783,0 days 02:28:20.239000,HAM,0 days 00:01:37.691000,34.0,INTERMEDIATE,2.0,Mercedes,True,9.0,1
784,0 days 02:29:51.696000,HAM,0 days 00:01:31.457000,35.0,INTERMEDIATE,3.0,Mercedes,True,9.0,1
785,0 days 02:31:20.459000,HAM,0 days 00:01:28.763000,36.0,INTERMEDIATE,4.0,Mercedes,True,9.0,12
786,0 days 02:32:47.985000,HAM,0 days 00:01:27.526000,37.0,INTERMEDIATE,5.0,Mercedes,True,9.0,1
787,0 days 02:34:14.355000,HAM,0 days 00:01:26.370000,38.0,INTERMEDIATE,6.0,Mercedes,True,9.0,12
788,0 days 02:35:53.096000,HAM,0 days 00:01:38.741000,39.0,INTERMEDIATE,7.0,Mercedes,False,9.0,124
789,0 days 02:37:42.970000,HAM,0 days 00:01:49.874000,40.0,INTERMEDIATE,8.0,Mercedes,False,9.0,4
790,0 days 02:39:48.267000,HAM,0 days 00:02:05.297000,41.0,INTERMEDIATE,9.0,Mercedes,False,9.0,4
791,0 days 02:41:56.378000,HAM,0 days 00:02:08.111000,42.0,INTERMEDIATE,10.0,Mercedes,False,9.0,41
792,0 days 02:43:31.015000,HAM,0 days 00:01:34.637000,43.0,INTERMEDIATE,11.0,Mercedes,True,11.0,12
793,0 days 02:44:56.792000,HAM,0 days 00:01:25.777000,44.0,INTERMEDIATE,12.0,Mercedes,True,11.0,21
794,0 days 02:46:21.617000,HAM,0 days 00:01:24.825000,45.0,INTERMEDIATE,13.0,Mercedes,True,11.0,1
795,0 days 02:47:46.239000,HAM,0 days 00:01:24.622000,46.0,INTERMEDIATE,14.0,Mercedes,True,11.0,1
796,0 days 02:49:11.033000,HAM,0 days 00:01:24.794000,47.0,INTERMEDIATE,15.0,Mercedes,True,11.0,1
797,0 days 02:50:35.279000,HAM,0 days 00:01:24.246000,48.0,INTERMEDIATE,16.0,Mercedes,True,11.0,1
798,0 days 02:51:59.299000,HAM,0 days 00:01:24.020000,49.0,INTERMEDIATE,17.0,Mercedes,True,11.0,1
799,0 days 02:53:22.997000,HAM,0 days 00:01:23.698000,50.0,INTERMEDIATE,18.0,Mercedes,True,11.0,1

In [ ]:
for key, value in sessions.items():
    n=len(value)
    i=0
    while i<n:
        os.makedirs(f"../data/{key}/{i+1}/",  exist_ok=True)
        sessions[key][i].laps.to_csv(f"../data/{key}/{i+1}/laps.csv", index=False)
        i+=1